import Foundation

/// Measures the WiFi link by whatever means the router will answer to.
///
/// The first hop is the one destination the phone cannot choose, so it
/// has to work with whatever that router permits. Three rungs are tried
/// in order and the first that answers wins:
///
/// 1. **ICMP echo.** The normal case.
/// 2. **An expiring TTL.** A router that drops packets addressed to
///    itself must still report an expired TTL, and the source of that
///    error is the router. This is how `mtr` measures hop 1 on the Pi.
/// 3. **TCP connect or refusal.** An RST is generated by the host's own
///    stack, so the time to receive one is a round trip even when no port
///    is open. The router does not have to offer a service, only to say
///    no.
///
/// Every rung tried is recorded, answered or not, so the app can report
/// what it did rather than offering the user a choice of explanations.
///
/// A note on history: this ladder was built after the app reported "your
/// router did not answer" on every network, which was attributed to
/// campus client isolation. The real cause was a parsing bug in
/// `ICMPPinger` (see Task 1 of the app redesign plan, which fixed
/// `parseReply` to skip the IPv4 header Darwin includes), and rung 1
/// works. The other two rungs are kept because routers that answer
/// nothing do exist, and because rung 2 is the method the Pi already
/// uses.
public enum GatewayProbe {

    /// Ports worth asking. Most gateways answer something on at least one,
    /// whether with a handshake or a refusal.
    public static let candidatePorts: [UInt16] = [80, 443, 53, 8080]

    public enum Method: String, Sendable, Equatable {
        case icmp         // the router answered echo requests
        case firstHopTTL  // it ignored echo but reported an expired TTL
        case tcp          // it answered TCP, possibly with a refusal
        case none         // it answered nothing at all
    }

    /// One rung, and what came of it.
    public struct Attempt: Sendable, Equatable {
        public let method: Method
        public let answered: Bool
        public let detail: String
    }

    public struct Result: Sendable, Equatable {
        public let summary: PingStats.Summary
        public let method: Method
        public let port: UInt16?
        public let attempts: [Attempt]
    }

    /// The four network operations the ladder needs, injectable so the
    /// order of the rungs can be tested without a router.
    public struct Probes: Sendable {
        public var echo: @Sendable (String, Int, TimeInterval) async throws -> PingStats.Summary
        public var firstHopTTL: @Sendable (String, Int, TimeInterval) async throws -> PingStats.Summary
        public var tcpPort: @Sendable (String) async -> UInt16?
        public var tcp: @Sendable (String, UInt16, Int, TimeInterval) async -> PingStats.Summary

        public init(
            echo: @escaping @Sendable (String, Int, TimeInterval) async throws -> PingStats.Summary,
            firstHopTTL: @escaping @Sendable (String, Int, TimeInterval) async throws -> PingStats.Summary,
            tcpPort: @escaping @Sendable (String) async -> UInt16?,
            tcp: @escaping @Sendable (String, UInt16, Int, TimeInterval) async -> PingStats.Summary
        ) {
            self.echo = echo
            self.firstHopTTL = firstHopTTL
            self.tcpPort = tcpPort
            self.tcp = tcp
        }

        public static let live = Probes(
            echo: { host, count, interval in
                try await ICMPPinger.ping(host: host, count: count, interval: interval)
            },
            firstHopTTL: { _, count, interval in
                try await ICMPPinger.firstHop(count: count, interval: interval)
            },
            tcpPort: { host in await respondingPort(host: host) },
            tcp: { host, port, count, interval in
                await tcpPing(host: host, port: port, count: count, interval: interval)
            })
    }

    public static func measure(host: String,
                               count: Int = 10,
                               interval: TimeInterval = 0.2,
                               probes: Probes = .live) async -> Result {
        var attempts: [Attempt] = []

        // Rung 1 and rung 2 are both ICMP and share their shape.
        for (method, probe) in [(Method.icmp, probes.echo),
                                (Method.firstHopTTL, probes.firstHopTTL)] {
            do {
                let summary = try await probe(host, count, interval)
                if summary.lossPct < 100 {
                    attempts.append(Attempt(method: method, answered: true,
                                            detail: "\(summary.rttMs) ms"))
                    return Result(summary: summary, method: method, port: nil,
                                  attempts: attempts)
                }
                attempts.append(Attempt(method: method, answered: false,
                                        detail: "no reply"))
            } catch {
                attempts.append(Attempt(method: method, answered: false,
                                        detail: String(describing: error)))
            }
        }

        // Rung 3.
        guard let port = await probes.tcpPort(host) else {
            attempts.append(Attempt(method: .tcp, answered: false,
                                    detail: "no candidate port answered"))
            return Result(summary: PingStats.summarise(rtts: [], sent: count),
                          method: .none, port: nil, attempts: attempts)
        }
        let summary = await probes.tcp(host, port, count, interval)
        let answered = summary.lossPct < 100
        attempts.append(Attempt(method: .tcp, answered: answered,
                                detail: answered ? "port \(port), \(summary.rttMs) ms"
                                                 : "port \(port) stopped answering"))
        return Result(summary: summary, method: answered ? .tcp : .none,
                      port: port, attempts: attempts)
    }

    /// Repeated TCP round trips to a port already known to answer.
    static func tcpPing(host: String, port: UInt16, count: Int,
                        interval: TimeInterval) async -> PingStats.Summary {
        let trustRefusals = LocalSubnet.isOnLink(host)
        var rtts: [Double] = []
        for index in 0..<count {
            switch await TCPProbe.probe(host: host, port: port) {
            case .connected(let rtt): rtts.append(rtt)
            case .refused(let rtt) where trustRefusals: rtts.append(rtt)
            case .refused, .unreachable: break
            }
            if index < count - 1, interval > 0 {
                try? await Task.sleep(nanoseconds: UInt64(interval * 1_000_000_000))
            }
        }
        return PingStats.summarise(rtts: rtts, sent: count)
    }

    /// The first candidate port that produces any answer, open or shut.
    ///
    /// A refusal counts only from an on-link address. The local stack
    /// refuses connections to unroutable addresses in a few milliseconds
    /// without sending anything, and that must never be mistaken for a
    /// router replying. See `LocalSubnet`.
    ///
    /// `probe` is injectable, separately from `Probes` above, because this
    /// function is also called directly by its own tests: the trust rule
    /// is what is under test, not any particular network's behaviour
    /// toward a reserved, unrouted address.
    static func respondingPort(host: String,
                               ports: [UInt16] = candidatePorts,
                               onLink: ((String) -> Bool) = LocalSubnet.isOnLink,
                               probe: @Sendable (String, UInt16) async -> TCPProbe.Outcome
                                   = { host, port in
                                       await TCPProbe.probe(host: host, port: port, timeout: 1)
                                   })
        async -> UInt16? {
        let trustRefusals = onLink(host)
        for port in ports {
            switch await probe(host, port) {
            case .connected: return port
            case .refused where trustRefusals: return port
            case .refused, .unreachable: continue
            }
        }
        return nil
    }
}
