import Foundation

/// Measures the WiFi link by whatever means the router will answer to.
///
/// The first hop is the one destination the phone cannot choose, so it has
/// to work with whatever the router permits. Observed on a campus network
/// (21 August 2026): the gateway address is correct and the app has local
/// network permission, yet it ignores ICMP echo entirely, which is
/// consistent with the client isolation already documented for that site.
///
/// The way round it is that a TCP **refusal** is still an answer. An RST
/// is generated by the host's own stack, so the time to receive one is a
/// genuine round trip even when no port is open. The router does not have
/// to offer a service; it only has to say no. This is the same reasoning
/// that put the Pi's cloud reference leg on TCP handshakes, taken one step
/// further.
public enum GatewayProbe {

    /// Ports worth asking. Most gateways answer something on at least one,
    /// whether with a handshake or a refusal.
    public static let candidatePorts: [UInt16] = [80, 443, 53, 8080]

    public enum Method: String, Sendable, Equatable {
        case icmp        // the router answered echo requests
        case tcp         // it ignored ICMP but answered TCP, possibly with RST
        case none        // it answered nothing at all
    }

    public struct Result: Sendable, Equatable {
        public let summary: PingStats.Summary
        public let method: Method
        public let port: UInt16?
    }

    public static func measure(host: String,
                               count: Int = 10,
                               interval: TimeInterval = 0.2) async -> Result {
        // ICMP first: it is the cheapest and needs no port to be chosen.
        if let icmp = try? await ICMPPinger.ping(host: host, count: count, interval: interval),
           icmp.lossPct < 100 {
            return Result(summary: icmp, method: .icmp, port: nil)
        }

        guard let port = await respondingPort(host: host) else {
            return Result(summary: PingStats.summarise(rtts: [], sent: count),
                          method: .none, port: nil)
        }

        let trustRefusals = LocalSubnet.isOnLink(host)
        var rtts: [Double] = []
        for index in 0..<count {
            switch await TCPProbe.probe(host: host, port: port) {
            case .connected(let rtt): rtts.append(rtt)
            case .refused(let rtt) where trustRefusals: rtts.append(rtt)
            case .refused, .unreachable: break
            }
            if index < count - 1 {
                try? await Task.sleep(nanoseconds: UInt64(interval * 1_000_000_000))
            }
        }
        return Result(summary: PingStats.summarise(rtts: rtts, sent: count),
                      method: .tcp, port: port)
    }

    /// The first candidate port that produces any answer, open or shut.
    ///
    /// A refusal counts only from an on-link address. The local stack
    /// refuses connections to unroutable addresses in a few milliseconds
    /// without sending anything, and that must never be mistaken for a
    /// router replying. See `LocalSubnet`.
    static func respondingPort(host: String,
                               ports: [UInt16] = candidatePorts,
                               onLink: ((String) -> Bool) = LocalSubnet.isOnLink)
        async -> UInt16? {
        let trustRefusals = onLink(host)
        for port in ports {
            switch await TCPProbe.probe(host: host, port: port, timeout: 1) {
            case .connected: return port
            case .refused where trustRefusals: return port
            case .refused, .unreachable: continue
            }
        }
        return nil
    }
}
