import Foundation
import Network
import os

/// TCP handshake RTT, mirroring `baseline._tcp_ping`.
///
/// Used for two things: hosts that drop ICMP echo (Azure App Service does,
/// which is why the cloud reference leg is probed this way), and the
/// latency samples in the bufferbloat workload, where TCP is chosen so the
/// measurement survives networks that filter ping.
public enum TCPProbe {

    /// What came back from a connection attempt.
    ///
    /// `refused` matters as much as `connected`. A TCP RST is generated by
    /// the host itself, so the time to receive one is a real round trip
    /// even though the port is shut. That is what makes it possible to
    /// measure a router which answers neither ICMP echo nor any service:
    /// it only has to answer *something*.
    public enum Outcome: Equatable, Sendable {
        case connected(Double)
        case refused(Double)
        case unreachable

        public var rttMs: Double? {
            switch self {
            case .connected(let ms), .refused(let ms): return ms
            case .unreachable: return nil
            }
        }
    }

    /// One handshake in ms, or nil if nothing came back. Both a completed
    /// handshake and a refusal count as a reply.
    public static func handshakeMs(host: String, port: UInt16 = 443,
                                   timeout: TimeInterval = 2) async -> Double? {
        await probe(host: host, port: port, timeout: timeout).rttMs
    }

    public static func probe(host: String, port: UInt16 = 443,
                             timeout: TimeInterval = 2) async -> Outcome {
        guard let port = NWEndpoint.Port(rawValue: port) else { return .unreachable }
        let connection = NWConnection(host: NWEndpoint.Host(host), port: port, using: .tcp)
        let start = Date()

        return await withCheckedContinuation { continuation in
            let finished = OSAllocatedUnfairLock(initialState: false)
            @Sendable func finish(_ value: Outcome) {
                let alreadyDone = finished.withLock { done -> Bool in
                    defer { done = true }
                    return done
                }
                guard !alreadyDone else { return }
                connection.cancel()
                continuation.resume(returning: value)
            }

            @Sendable func classify(_ error: NWError) -> Outcome {
                // A refusal is an answer. Anything else (no route, timed
                // out, filtered) means nothing came back and must not be
                // recorded as a round trip.
                if case .posix(let code) = error, code == .ECONNREFUSED || code == .ECONNRESET {
                    return .refused(Date().timeIntervalSince(start) * 1000)
                }
                return .unreachable
            }

            connection.stateUpdateHandler = { state in
                switch state {
                case .ready:
                    finish(.connected(Date().timeIntervalSince(start) * 1000))
                case .waiting(let error):
                    // NWConnection reports a refusal as `waiting` and then
                    // retries. There is nothing to wait for, so take the
                    // timing and stop.
                    if case .refused = classify(error) { finish(classify(error)) }
                case .failed(let error):
                    finish(classify(error))
                case .cancelled:
                    finish(.unreachable)
                default:
                    break
                }
            }
            connection.start(queue: .global(qos: .userInitiated))
            DispatchQueue.global().asyncAfter(deadline: .now() + timeout) { finish(.unreachable) }
        }
    }

    /// A run of handshakes, summarised like a ping run. Resolution happens
    /// once up front so DNS time is not folded into the RTT samples.
    public static func probe(host: String, port: UInt16 = 443,
                             count: Int = 10,
                             interval: TimeInterval = 0.2) async -> PingStats.Summary {
        var rtts: [Double] = []
        for index in 0..<count {
            if let rtt = await handshakeMs(host: host, port: port) { rtts.append(rtt) }
            if index < count - 1 {
                try? await Task.sleep(nanoseconds: UInt64(interval * 1_000_000_000))
            }
        }
        return PingStats.summarise(rtts: rtts, sent: count)
    }
}
